version: '2'
services:
  ops:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./ops/logs:/opt/mongodb/mms/logs
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    volumes:
      - ./ops/dbdata:/data/db
    ports:
      - 27017:27017